@echo off
start "" /MAX "C:\Users\Public\Desktop\VMQuickConfig"
python -c "import pyautogui as pag; pag.click(143, 487, duration=5)"
python -c "import pyautogui as pag; pag.click(155, 554, duration=2)"
python -c "import pyautogui as pag; pag.click(637, 417, duration=2)"
python -c "import pyautogui as pag; pag.click(588, 10, duration=2)"
echo ..........................................................
echo .....Brought By Tsubasa...............................
echo ..............................................................
echo ..........................................................
echo ......... Discord Server - https://discord.gg/WvFK2Dfw ....
echo ..........................................................
echo ..Youtube Channel - https://www.youtube.com/@HyugaKojirolol..
echo ..........................................................
echo User name : tsubasav2
echo User Pass : Tsubasa0235
